import { expect, test } from "@playwright/test";
import c2 from "../../src/data/case02.json" with { type: "json" };
import c3 from "../../src/data/case03.json" with { type: "json" };
import c4 from "../../src/data/case04.json" with { type: "json" };
import c5 from "../../src/data/case05.json" with { type: "json" };
import c6 from "../../src/data/case06.json" with { type: "json" };
import type { Scenario } from "../../src/scenario/types";
import { assertScenario } from "../../src/scenario/validate";
import { start, tab, readAll, fill, submit, noOverflow, openReportGroup } from "../helpers/play";
import { correctReport } from "../helpers/report";
const episodes: Scenario[] = [c2,c3,c4,c5,c6].map(value => { assertScenario(value); return value; });
for (const scenario of episodes) test(scenario.id + " desktop dialogue, investigation, grade and reload", async ({ page }, info) => {
  const errors: string[] = []; page.on("pageerror", e => errors.push(e.message));
  await page.goto("/#list");
  await expect(page.locator(".case-card")).toHaveCount(6);
  await page.locator(`[data-case-id="${scenario.id}"]`).getByRole("button", {name:"依頼を開く"}).click();
  const intro = page.getByRole("region", {name:"依頼人との会話"});
  await expect(intro.locator(".conversation-controls")).toContainText("1 / 8");
  await intro.getByRole("button", {name:"次の発言"}).click();
  await expect(intro.locator(".conversation-controls")).toContainText("2 / 8");
  await intro.getByRole("button", {name:"前の発言"}).click();
  await page.getByRole("button", {name:"現場の調査を始める"}).click();
  await expect(tab(page,"構成")).toBeVisible();
  await expect(page.getByText(scenario.solution.causalChain[0].text,{exact:true})).not.toBeVisible();
  await readAll(page,scenario);
  await fill(page,correctReport(scenario.solution),scenario);
  await noOverflow(page);
  await submit(page);
  await expect(page.locator(".score")).toHaveText("100/100");
  await expect(page.locator(".result-banner h1")).toHaveText("解決");
  await expect(page.getByRole("region",{name:"報告後の会話"})).toBeVisible();
  await page.reload();
  await expect(page.locator(".score")).toHaveText("100/100");
  await page.locator(".evidence-refs button").first().click();
  await expect(page.getByText("解説から証拠を確認中 · 閲覧のみ")).toBeVisible();
  await page.getByRole("button",{name:"解説へ戻る"}).click();
  await page.getByRole("button",{name:"事件一覧へ",exact:true}).last().click();
  await expect(page.locator(`[data-case-id="${scenario.id}"] .record-summary`)).toContainText("初回 100点");
  expect(errors).toEqual([]);
});

test("same evidence IDs and options stay independent between episodes", async ({page}) => {
  await start(page,"case02");
  await tab(page,"証拠").click();
  await page.getByRole("checkbox",{name:"E01を確認済みにする",exact:true}).check();
  await page.locator('[data-evidence-id="E01"]').click();
  await tab(page,"報告").click();
  await openReportGroup(page,"scopeId");
  await page.locator('input[name="scopeId"]').first().check();
  await page.getByRole("button",{name:"事件一覧へ",exact:true}).click();
  await page.locator('[data-case-id="case03"]').getByRole("button",{name:"依頼を開く"}).click();
  await page.getByRole("button",{name:"現場の調査を始める"}).click();
  await tab(page,"証拠").click();
  await expect(page.getByText(`閲覧 0/${c3.evidence.length}`,{exact:true})).toBeVisible();
  await expect(page.getByRole("checkbox",{name:"E01を確認済みにする",exact:true})).not.toBeChecked();
  await page.getByRole("button",{name:"事件一覧へ",exact:true}).click();
  await page.locator('[data-case-id="case02"]').getByRole("button",{name:"続きから調査する"}).click();
  await tab(page,"証拠").click();
  await expect(page.getByRole("checkbox",{name:"E01を確認済みにする",exact:true})).toBeChecked();
  await expect(page.getByText(`閲覧 1/${c2.evidence.length}`,{exact:true})).toBeVisible();
  await page.reload();
  await expect(page.getByRole("checkbox",{name:"E01を確認済みにする",exact:true})).toBeChecked();
  await tab(page,"報告").click();
  await openReportGroup(page,"scopeId");
  await expect(page.locator('input[name="scopeId"]').first()).toBeChecked();
});

test("a new case remains playable when initial storage is unavailable", async ({page}) => {
  await page.addInitScript(() => { Storage.prototype.setItem = () => { throw new DOMException("full","QuotaExceededError"); }; });
  await start(page,"case06");
  await expect(page.getByText("保存不可",{exact:true})).toBeVisible();
  await tab(page,"証拠").click();
  await expect(page.locator(".evidence-card")).toHaveCount(c6.evidence.length);
});
